# Generated by Django 3.1 on 2020-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20200901_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('Mr', 'mr'), ('Mrs', 'mrs'), ('Miss', 'miss')], max_length=10),
        ),
    ]
